let name = "Jitender";
let school = "SND public school";
let grade = "B1";
let section = "C"
let rollno = 14;
let englishmarks = 89;
let mathsmarks = 75;
let sciencemarks = 65;
console.log("Name = " + name);
console.log("School = " + school);
console.log("Grade = " + grade);
console.log("Section = " + section);
console.log("Rollno = " + rollno);
console.log("English Marks = " + englishmarks);
console.log("Maths Marks = " + mathsmarks);
console.log("Science Marks = " + sciencemarks);
